// <auto-generated />
namespace TicketSysteemMVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ticketmeerderetechnicussen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketmeerderetechnicussen));
        
        string IMigrationMetadata.Id
        {
            get { return "201912181055343_ticket-meerdere-technicussen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
